image: registry.gitlab.com/buddybot3/control/android-app-builder:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true"

stages:
  - build
  - test
  - analyze

# Адаптивный билд: debug для всего, release — только для master
build:
  stage: build
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "master" || "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "master" ]]; then
        echo "Building release..."
        ./gradlew assembleRelease
      else
        echo "Building debug..."
        ./gradlew assembleDebug
      fi
  only:
    - merge_requests
    - main
    - develop
    - master

test:
  stage: test
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "master" || "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "master" ]]; then
        echo "Running release tests and lint..."
        ./gradlew testReleaseUnitTest lintRelease
      else
        echo "Running debug tests and lint..."
        ./gradlew testDebugUnitTest lintDebug
      fi
  artifacts:
    reports:
      junit:
        - app/build/test-results/testDebugUnitTest/TEST-*.xml
        - app/build/test-results/testReleaseUnitTest/TEST-*.xml
      codequality:
        - app/build/reports/lint-results-debug.sarif
        - app/build/reports/lint-results-release.sarif
    paths:
      - app/build/reports/lint-results-debug.html
      - app/build/reports/lint-results-release.html
    expire_in: 1 week
  only:
    - merge_requests
    - main
    - develop
    - master

sonarcloud-analysis:
  stage: analyze
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "master" || "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "master" ]]; then
        export BUILD_TYPE="release"
      else
        export BUILD_TYPE="debug"
      fi

      export SONAR_SOURCES="app/src/main/java"
      export SONAR_TESTS="app/src/test/java"
      export SONAR_BINARIES="app/build/tmp/kotlin-classes/$BUILD_TYPE,app/build/intermediates/compile_app_classes_jar/$BUILD_TYPE"

      sonar-scanner \
        -Dsonar.projectKey=$SONAR_PROJECT_KEY \
        -Dsonar.organization=$SONAR_ORGANIZATION \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.sources=$SONAR_SOURCES \
        -Dsonar.tests=$SONAR_TESTS \
        -Dsonar.java.binaries=$SONAR_BINARIES \
        -Dsonar.pullrequest.key=$CI_MERGE_REQUEST_IID \
        -Dsonar.pullrequest.branch=$CI_COMMIT_REF_NAME \
        -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  only:
    - merge_requests
    - main
    - develop
    - master
